#include "soundboard_tunes.h"

#define HOMECOMING_LENGTH(x) ((x) * 6)
#define HOMECOMING_NOTE(x) (((x) == BUZZER_NOTE_REST) ? (x) : ((x) + 14))

#define GHOST_LENGTH(x) ((x) * 5)

#define TAKE_ON_ME_LENGTH(x) ((x) * 5)
#define TAKE_ON_ME_NOTE(x) (((x) == BUZZER_NOTE_REST) ? (x) : ((x) - 3))

#define AIRFLOW_NOTE(x) (((x) == BUZZER_NOTE_REST) ? (x) : ((x) + 12))

int8_t take_on_me_tune[] = {
	TAKE_ON_ME_NOTE(BUZZER_NOTE_A5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_A5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_F5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_D5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(3),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_D5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(3),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_G5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(3),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_G5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(3),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_G5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_B5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_B5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_C6), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_D6), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),

    TAKE_ON_ME_NOTE(BUZZER_NOTE_C6), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_C6), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_C6), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_G5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(3),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_F5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(3),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_A5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(3),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_A5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(3),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_A5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_G5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_G5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_A5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_G5), TAKE_ON_ME_LENGTH(1),
    TAKE_ON_ME_NOTE(BUZZER_NOTE_REST), TAKE_ON_ME_LENGTH(1),

    0
};

int8_t homecoming_tune[] = {
    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C4), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_G5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),

    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_A3), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_G5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),

    HOMECOMING_NOTE(BUZZER_NOTE_F5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_B4), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_B4), HOMECOMING_LENGTH(2),

    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_F5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_G5), HOMECOMING_LENGTH(4),
    HOMECOMING_NOTE(BUZZER_NOTE_G4), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),

    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C4), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_G5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),

    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_A3), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_G5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(2),

    HOMECOMING_NOTE(BUZZER_NOTE_F5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_E5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_B4), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_D5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_B4), HOMECOMING_LENGTH(2),

    HOMECOMING_NOTE(BUZZER_NOTE_C5), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_G4), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_E4), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_G4), HOMECOMING_LENGTH(2),
    HOMECOMING_NOTE(BUZZER_NOTE_C4), HOMECOMING_LENGTH(4),
    HOMECOMING_NOTE(BUZZER_NOTE_REST), HOMECOMING_LENGTH(4),

    0
};

int8_t friendly_ghost_tune[] = {
	BUZZER_NOTE_F5SHARP_G5FLAT, GHOST_LENGTH(1),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),
    BUZZER_NOTE_G5SHARP_A5FLAT, GHOST_LENGTH(1),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),
    BUZZER_NOTE_A5, GHOST_LENGTH(1),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),
    BUZZER_NOTE_G5SHARP_A5FLAT, GHOST_LENGTH(1),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),
    BUZZER_NOTE_F3SHARP_G3FLAT, GHOST_LENGTH(2),
    BUZZER_NOTE_REST, GHOST_LENGTH(2),
    BUZZER_NOTE_F5SHARP_G5FLAT, GHOST_LENGTH(2),
    BUZZER_NOTE_REST, GHOST_LENGTH(2),

    BUZZER_NOTE_C7SHARP_D7FLAT, GHOST_LENGTH(2),
    BUZZER_NOTE_A6, GHOST_LENGTH(2),
    BUZZER_NOTE_G6SHARP_A6FLAT, GHOST_LENGTH(2),
    BUZZER_NOTE_F6SHARP_G6FLAT, GHOST_LENGTH(2),
    BUZZER_NOTE_C6SHARP_D6FLAT, GHOST_LENGTH(4),
    BUZZER_NOTE_F3SHARP_G3FLAT, GHOST_LENGTH(3),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),

    BUZZER_NOTE_F5SHARP_G5FLAT, GHOST_LENGTH(1),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),
    BUZZER_NOTE_G5SHARP_A5FLAT, GHOST_LENGTH(1),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),
    BUZZER_NOTE_A5, GHOST_LENGTH(1),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),
    BUZZER_NOTE_G5SHARP_A5FLAT, GHOST_LENGTH(1),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),
    BUZZER_NOTE_E3, GHOST_LENGTH(2),
    BUZZER_NOTE_REST, GHOST_LENGTH(2),
    BUZZER_NOTE_F5SHARP_G5FLAT, GHOST_LENGTH(2),
    BUZZER_NOTE_REST, GHOST_LENGTH(2),

    BUZZER_NOTE_B6, GHOST_LENGTH(2),
    BUZZER_NOTE_G6SHARP_A6FLAT, GHOST_LENGTH(2),
    BUZZER_NOTE_E6, GHOST_LENGTH(2),
    BUZZER_NOTE_G6SHARP_A6FLAT, GHOST_LENGTH(2),
    BUZZER_NOTE_B6, GHOST_LENGTH(4),
    BUZZER_NOTE_E3, GHOST_LENGTH(3),
    BUZZER_NOTE_REST, GHOST_LENGTH(1),

    0
};

int8_t airflow_tune[] = {
    AIRFLOW_NOTE(BUZZER_NOTE_F5SHARP_G5FLAT), 12,
    AIRFLOW_NOTE(BUZZER_NOTE_G5SHARP_A5FLAT), 12,
    AIRFLOW_NOTE(BUZZER_NOTE_A5), 24,
    AIRFLOW_NOTE(BUZZER_NOTE_E5), 24,
    AIRFLOW_NOTE(BUZZER_NOTE_D5SHARP_E5FLAT), 24,
    AIRFLOW_NOTE(BUZZER_NOTE_A5), 19,
    AIRFLOW_NOTE(BUZZER_NOTE_G5SHARP_A5FLAT), 3,
    AIRFLOW_NOTE(BUZZER_NOTE_A5), 3,
    AIRFLOW_NOTE(BUZZER_NOTE_G5SHARP_A5FLAT), 24,
    AIRFLOW_NOTE(BUZZER_NOTE_D5SHARP_E5FLAT), 24,
    AIRFLOW_NOTE(BUZZER_NOTE_C5SHARP_D5FLAT), 36,

    AIRFLOW_NOTE(BUZZER_NOTE_D5SHARP_E5FLAT), 6,
    AIRFLOW_NOTE(BUZZER_NOTE_E5), 6,
    AIRFLOW_NOTE(BUZZER_NOTE_F5SHARP_G5FLAT), 48,
    AIRFLOW_NOTE(BUZZER_NOTE_C5SHARP_D5FLAT), 24,
    AIRFLOW_NOTE(BUZZER_NOTE_F5SHARP_G5FLAT), 24,
    AIRFLOW_NOTE(BUZZER_NOTE_E5), 36,
    AIRFLOW_NOTE(BUZZER_NOTE_D5SHARP_E5FLAT), 3,
    AIRFLOW_NOTE(BUZZER_NOTE_E5), 3,
    AIRFLOW_NOTE(BUZZER_NOTE_D5SHARP_E5FLAT), 36,
    AIRFLOW_NOTE(BUZZER_NOTE_E5), 9,
    AIRFLOW_NOTE(BUZZER_NOTE_REST), 3,
    AIRFLOW_NOTE(BUZZER_NOTE_E5), 48,
    AIRFLOW_NOTE(BUZZER_NOTE_REST), 48,

    0
};

int8_t zelda_secret_tune[] = {
    BUZZER_NOTE_G5, 8,
    BUZZER_NOTE_F5SHARP_G5FLAT, 8,
    BUZZER_NOTE_D5SHARP_E5FLAT, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_G4SHARP_A4FLAT, 8,
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_G5SHARP_A5FLAT, 8,
    BUZZER_NOTE_C6, 20,
    0
};

int8_t zelda_fairy_tune[] = {
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_F4, 8,

    BUZZER_NOTE_D5, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_F4, 8,

    BUZZER_NOTE_C5SHARP_D5FLAT, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_F4, 8,

    BUZZER_NOTE_D5, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_F4, 8,
    // -------------------------------
    BUZZER_NOTE_D5, 8,
    BUZZER_NOTE_E4, 8,
    BUZZER_NOTE_G4, 8,
    BUZZER_NOTE_E4, 8,

    BUZZER_NOTE_C5, 8,
    BUZZER_NOTE_E4, 8,
    BUZZER_NOTE_G4, 8,
    BUZZER_NOTE_E4, 8,

    BUZZER_NOTE_B4, 8,
    BUZZER_NOTE_E4, 8,
    BUZZER_NOTE_G4, 8,
    BUZZER_NOTE_E4, 8,

    BUZZER_NOTE_C5, 8,
    BUZZER_NOTE_E4, 8,
    BUZZER_NOTE_G4, 8,
    BUZZER_NOTE_E4, 8,
    // -------------------------------
    BUZZER_NOTE_C5, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_D4, 8,

    BUZZER_NOTE_B4, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_D4, 8,

    BUZZER_NOTE_A4SHARP_B4FLAT, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_D4, 8,

    BUZZER_NOTE_B4, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_D4, 8,
    // -------------------------------
    BUZZER_NOTE_B4, 8,
    BUZZER_NOTE_C4, 8,
    BUZZER_NOTE_E4, 8,
    BUZZER_NOTE_C4, 8,

    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_C4, 8,
    BUZZER_NOTE_E4, 8,
    BUZZER_NOTE_C4, 8,

    BUZZER_NOTE_G4SHARP_A4FLAT, 8,
    BUZZER_NOTE_C4, 8,
    BUZZER_NOTE_E4, 8,
    BUZZER_NOTE_C4, 8,

    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_C4, 8,
    BUZZER_NOTE_E4, 8,
    BUZZER_NOTE_C4, 8,
    // -------------------------------
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_F4, 8,

    BUZZER_NOTE_D5, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_F4, 8,

    BUZZER_NOTE_C5SHARP_D5FLAT, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_F4, 8,

    BUZZER_NOTE_D5, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_F4, 8,
    // -------------------------------
    BUZZER_NOTE_F5, 8,
    BUZZER_NOTE_G4, 8,
    BUZZER_NOTE_A4SHARP_B4FLAT, 8,
    BUZZER_NOTE_G4, 8,

    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_G4, 8,
    BUZZER_NOTE_A4SHARP_B4FLAT, 8,
    BUZZER_NOTE_G4, 8,

    BUZZER_NOTE_D5SHARP_E5FLAT, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_C5SHARP_D5FLAT, 8,
    BUZZER_NOTE_A4, 8,

    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_C5SHARP_D5FLAT, 8,
    BUZZER_NOTE_G4, 8,
    // -------------------------------
    BUZZER_NOTE_G5, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_D4, 8,

    BUZZER_NOTE_F5, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_D4, 8,

    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_D4, 8,

    BUZZER_NOTE_D5, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_D4, 8,
    // -------------------------------
    BUZZER_NOTE_C5, 8,
    BUZZER_NOTE_G3, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_G3, 8,

    BUZZER_NOTE_B4, 8,
    BUZZER_NOTE_G3, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_G3, 8,

    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_G3, 8,
    BUZZER_NOTE_F4, 8,
    BUZZER_NOTE_G3, 8,

    BUZZER_NOTE_G4, 8,
    BUZZER_NOTE_B3, 8,
    BUZZER_NOTE_D4, 8,
    BUZZER_NOTE_G3, 8,

    0
};

int8_t thomas_theme_tune[] = {
    BUZZER_NOTE_G5, 8,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_A5, 8,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_B5, 8,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_C6, 16,
    BUZZER_NOTE_REST, 16,
    BUZZER_NOTE_D6, 8,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_E6, 16,
    BUZZER_NOTE_REST, 16,
    BUZZER_NOTE_G5SHARP_A5FLAT, 16,
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_G5SHARP_A5FLAT, 16,
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_G5SHARP_A5FLAT, 16,
    BUZZER_NOTE_D5, 8,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_G5SHARP_A5FLAT, 16,
    BUZZER_NOTE_D5, 8,
    0
};

int8_t mario_theme_tune[] = {
    BUZZER_NOTE_E6, 7,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_E6, 7,
    BUZZER_NOTE_REST, 10,
    BUZZER_NOTE_E6, 7,
    BUZZER_NOTE_REST, 11,
    BUZZER_NOTE_C6, 7,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E6, 7,
    BUZZER_NOTE_REST, 10,
    BUZZER_NOTE_G6, 8,
    BUZZER_NOTE_REST, 30,
    BUZZER_NOTE_G5, 20,
    0
};

int8_t mgs_codec_tune[] = {
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_REST, 6,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    BUZZER_NOTE_G5SHARP_A5FLAT, 1,
    BUZZER_NOTE_C6, 1,
    0
};

int8_t kim_possible_tune[] = {
    BUZZER_NOTE_G7, 6,
    BUZZER_NOTE_G4, 2,
    BUZZER_NOTE_REST, 5,
    BUZZER_NOTE_G7, 6,
    BUZZER_NOTE_G4, 2,
    BUZZER_NOTE_REST, 5,
    BUZZER_NOTE_A7SHARP_B7FLAT, 6,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_G7, 6,
    BUZZER_NOTE_G4, 2,
    0
};

int8_t power_rangers_tune[] = {
    BUZZER_NOTE_D6, 6,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_D6, 6,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_C6, 6,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_D6, 6,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_F6, 6,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_D6, 24,
    0
};

int8_t layla_tune[] = {
    BUZZER_NOTE_A5, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_C6, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_D6, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F6, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_D6, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_C6, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_D6, 20,
    0
};

int8_t harry_potter_tune[] = {
    BUZZER_NOTE_B4, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E5, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_G5, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F5SHARP_G5FLAT, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E5, 16,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_B5, 8,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_A5, 24,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F5SHARP_G5FLAT, 24,
    0
};

int8_t harry_potter_long_tune[] = {
    BUZZER_NOTE_B4, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E5, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_G5, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F5SHARP_G5FLAT, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E5, 16,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_B5, 8,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_A5, 24,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F5SHARP_G5FLAT, 24,
    BUZZER_NOTE_REST, 1,

    BUZZER_NOTE_E5, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_G5, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F5SHARP_G5FLAT, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_D5SHARP_E5FLAT, 16,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F5, 8,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_B4, 24,
    0
};
